import type { Metadata } from "next";
import localFont from "next/font/local";
import Link from "next/link";

import {
  ModeToggle,
  ThemeProvider,
} from "@forthtilliath/forth-ui/components/mode-toggle";
import { Navbar } from "@forthtilliath/shadcn-ui/components/blocks/navbar-02";

import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "@forthtilliath Web",
  description: "Generated by create next app",
};

interface Item {
  href: string;
  label: string;
}

const items: Item[] = [
  { href: "#", label: "Home" },
  {
    label: "Foods",
    href: "#",
  },
  {
    label: "Travel",
    href: "#",
  },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // next-themes sets the theme class on <html> before hydration.
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar
            logo={<h1>Logo</h1>}
            items={items}
            render={({ href, label }) => <Link href={href}>{label}</Link>}
          />
          <main className="container p-8">{children}</main>
          <ModeToggle className="fixed right-4 bottom-4" />
        </ThemeProvider>
      </body>
    </html>
  );
}
